figure
subplot(3,2,1)
plot(out.time.Data,out.x_disp.Data,'r','LineWidth',2)
xlim([0 20])
ylim([-0.22 0.22])
sgtitle('Gaussian Noise Plots')
title('x Displacement')
xlabel('Time (s)')
ylabel('Displacement (m)')

subplot(3,2,3)
plot(out.time.Data,out.y_disp.Data,'r','LineWidth',2)
xlim([0 20])
ylim([-0.18 0.2])
title('y Displacement')
xlabel('Time (s)')
ylabel('Displacement (m)')

subplot(3,2,5)
plot(out.time.Data,out.z_disp.Data,'r','LineWidth',2)
xlim([0 20])
ylim([-0.27 0.22])
title('z Displacement')
xlabel('Time (s)')
ylabel('Displacement (m)')

subplot(3,2,2)
plot(out.time.Data,out.x_angle.Data,'r','LineWidth',2)
xlim([0 20])
ylim([-17 17])
title('x Angle')
xlabel('Time (s)')
ylabel('Angle (deg)')

subplot(3,2,4)
plot(out.time.Data,out.y_angle.Data,'r','LineWidth',2)
xlim([0 20])
ylim([-19 19])
title('y Angle')
xlabel('Time (s)')
ylabel('Angle (deg)')

subplot(3,2,6)
plot(out.time.Data,out.z_angle.Data,'r','LineWidth',2)
xlim([0 20])
ylim([-17 17])
title('z Angle')
xlabel('Time (s)')
ylabel('Angle (deg)')
